name: CI
on:
  push:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'

      - name: Install npm dependencies
        run: npm install

      - name: Migrate local sqlite DB for server side tests
        run: npx wrangler d1 migrations apply timely-tasker-dev --local <<< $'y\n'

      - name: Cypress run
        run: npm test
        env:
          # See issue https://github.com/cypress-io/cypress/issues/25357
          ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
         files: .nyc_output/out.json
