name: CI
on:
  push:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          component: true
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
         files: .nyc_output/out.json
      - name: Push result to Testspace server
        run: |
          testspace test-results.xml
        if: always()

